### ISSUE TITLE
Repo public

### ISSUE THREAD

**Issue by emuskardin** [MaxiSchwindler/KV#1]
Hi,
Can you please make the repo public?
Code is quite good now and all we want, some more testing and minor optimizations and I would like to merge it and create a new relase.

Dfa, Mealy, and Moore learning are all very efficient, that is they require muuuuch less queries than L*, though the algorithm itself is slower. 
Sifting is to blame, as for each transition you have to do the procedure... But I think we can try adding a cache also for that, but this is minor thing :)

Thank you :)

**Comment by MaxiSchwindler** [comment]
Done! Renamed the repo & set it public.
